import Layout from 'components/Layout'
import Head from 'next/head'
import React, { useEffect } from 'react'
import { trpc } from 'utils/trpc'
import styles from '../../../styles/Home.module.css'

export default function Prodotto() {

  const prodTrpc = trpc.useQuery(['prodotto.list', { fornitore: 1 }])
  useEffect(() => {

  }, [])


  if (!prodTrpc.isSuccess) return (
    <div>Not ready</div>
  )

  return (
    <Layout>
      <div className="container">
        <Head>
          <title>Prodotti</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Prodotti</h1>
          <div>
            <ul>
              {prodTrpc.data.map(prod => (
                <li key={prod.id} ><>{prod.nome}: {prod.prezzo}</></li>
              ))}
            </ul>
          </div>
        </main>
      </div>
    </Layout>
  )
}

