import Head from 'next/head'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Gest Care</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Index page</h1>
      </main>
    </div>
  )
}
