import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Index page</h1>
        <h2>If you logged in, your username is: </h2>

        <div>
          <a href="prodotto">
            <h2>Go to prodotti &rarr;</h2>
            <p>Pagina che serve a leggere o modificare la lista di prodotti</p>
          </a>
        </div>
      </main>
    </div>
  )
}
